#!/bin/sh

# TODO: Syntax???!!!
if [ $1 = "debug" ]; then
    time zig build-exe src/matx.zig --name matx --color on --cache-dir .cache/ -fno-emit-bin -freference-trace=16 -ODebug -fvalgrind
    if [ $? = 0 ]; then
        strace -cw ./matx
        valgrind --leak-check=full --show-leak-kinds=all ./matx
        # TODO: Tracy!
    fi
else
    # zig build-exe --help | less
    time zig build-exe src/matx.zig --name matx --color on --cache-dir .cache/ -freference-trace=16 -OReleaseSmall -static -fllvm -flld -flto -fstrip -fno-stack-check -fno-stack-protector # -fno-unwind-tables -fno-compiler-rt -fsingle-threaded -fdll-export-fns
    if [ $? = 0 ]; then
        strip -R.comment matx
    fi
fi
